"""Add fraud detection fields

Revision ID: 082ff29aae10
Revises: 
Create Date: 2025-09-13 04:02:03.071310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082ff29aae10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('marks')

    with op.batch_alter_table('legacy_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fraud_risk', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fraud_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fraud_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requires_manual_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legacy_documents', schema=None) as batch_op:
        batch_op.drop_column('requires_manual_review')
        batch_op.drop_column('fraud_analysis')
        batch_op.drop_column('fraud_score')
        batch_op.drop_column('fraud_risk')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
